M48
; DRILL file {KiCad 7.0.11-rc3} date Fri Dec  5 15:52:15 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-05T15:52:15+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-rc3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.4421Y-3.5945
T2
X5.7657Y-3.5945
M30
